#!/bin/bash

ROOT_DIR=`pwd`
THIRD_PARTY_DIR=$ROOT_DIR/third-party
BUILD_DIR=$ROOT_DIR/build
SRC_DIR=$ROOT_DIR/src
POST_DIR=$ROOT_DIR/posts

PYTHON_BIN=python2.7
TITLE="a note for myselves"
AUTHOR="Ken Ko"
POST_LIST=""

