#!/bin/bash

ROOT_DIR=`pwd`
THIRD_PARTY_DIR=$ROOT_DIR/third-party
BUILD_DIR=$ROOT_DIR/build
SRC_DIR=$ROOT_DIR/src
POST_DIR=$ROOT_DIR/posts

LIVE_DIR=~/webapps/relurori_root/blog
LIVE_PATH="http://www.relurori.com/blog"

PYTHON_BIN=python2.7
TITLE="relu.rori tech notes"
AUTHOR="Ken Ko"
POST_LIST=""

